version: '3'
services:
  mysql-dev: 
    # image: "mysql:5.7.41"
    image: "mysql:8.0.33"
    container_name: "mysql-dev"
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "mydb"
  postgres-dev: 
    image: "postgres:12.21"
    container_name: "postgres-dev"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  flyway:
    image: flyway/flyway:7.15
    container_name: "flyway"
    command: -url=jdbc:mysql://root:password@mysql-dev:3306/mydb -connectRetries=60 migrate
    volumes:
      - ./dbschema:/flyway/sql
    depends_on:
      - mysql-dev
  sqlite-flyway:
    image: flyway/flyway:7.15
    container_name: "sqlite_flyway"
    command: -url=jdbc:sqlite:/flyway/db/mydb.db migrate
    volumes:
      - .:/flyway/db
      - ./sqlite-migrations:/flyway/sql
  sqlite-attached-flyway:
    image: flyway/flyway:7.15
    container_name: "sqlite_attached_flyway"
    command: -url=jdbc:sqlite:/flyway/db/users.db migrate
    volumes:
      - .:/flyway/db
      - ./sqlite-attached-migrations:/flyway/sql
  postgres-flyway:
    image: flyway/flyway:7.15
    container_name: "postgres_flyway"
    command: -url=jdbc:postgresql://postgres-dev:5432/postgres -schemas=public -user=postgres -password=password -connectRetries=60 migrate
    volumes:
      - ./migrations/postgres:/flyway/sql
    depends_on:
      - postgres-dev