CREATE TABLE books(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    isbn TEXT NOT NULL
);

CREATE TABLE authors(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fullName TEXT NOT NULL,
    shortName TEXT
);

CREATE TABLE books_authors(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    book_id BIGINT UNSIGNED NOT NULL,
    author_id BIGINT UNSIGNED NOT NULL,
    author_ordinal INT NOT NULL,
    FOREIGN KEY (book_id) REFERENCES books (id)
);