CREATE TABLE IF NOT EXISTS movies(
	id INTEGER PRIMARY KEY,
	title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS persons(
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS actors(
	id INTEGER PRIMARY KEY,
	person_id INTEGER NOT NULL UNIQUE,
	movie_id INTEGER NOT NULL,
	FOREIGN KEY (person_id) REFERENCES persons (id)
	FOREIGN KEY (movie_id) REFERENCES movies (id)
);

CREATE TABLE IF NOT EXISTS reviews(
	id INTEGER PRIMARY KEY,
	rating INTEGER NOT NULL,
	movie_id INTEGER NOT NULL,
	FOREIGN KEY (movie_id) REFERENCES movies (id)
);