CREATE TABLE mytable1 (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  value INTEGER
);

CREATE TABLE mytable2 (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT,
  descr TEXT
);

CREATE TABLE mytable3 (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  double_value real,
  name TEXT NOT NULL
);
